// examples/react-example.tsx
/**
 * Dashgram SDK - React Example
 *
 * This example shows how to integrate Dashgram SDK in a React application.
 * Install the package: npm install @dashgram/javascript
 */

import React, { useEffect } from "react"
import DashgramMini from "@dashgram/javascript"

// Initialize SDK once when app loads
DashgramMini.init({
  projectId: process.env.REACT_APP_DASHGRAM_PROJECT_ID || "your-project-id",
  apiKey: process.env.REACT_APP_DASHGRAM_API_KEY || "your-api-key",
  trackLevel: 2, // Track interactions (clicks, form submissions, etc.)
  debug: process.env.NODE_ENV === "development"
})

function App() {
  useEffect(() => {
    // Track page view when component mounts
    DashgramMini.track("screen_view", {
      screen_name: "home",
      screen_path: "/"
    })
  }, [])

  const handleSubscribe = () => {
    DashgramMini.track("subscription_started", {
      plan: "premium",
      price: 9.99,
      currency: "USD"
    })
    // Your subscription logic here
  }

  const handlePurchase = (productId: string, price: number) => {
    DashgramMini.track("purchase_completed", {
      product_id: productId,
      amount: price,
      currency: "USD",
      payment_method: "card"
    })
    // Your purchase logic here
  }

  const handleUserLogin = (userId: string, userEmail: string) => {
    DashgramMini.identify(userId, {
      email: userEmail,
      plan: "free",
      signup_date: new Date().toISOString()
    })
  }

  return (
    <div>
      <h1>My Telegram Mini App</h1>
      <button onClick={handleSubscribe}>Subscribe</button>
      <button onClick={() => handlePurchase("product-123", 19.99)}>Buy Product</button>
    </div>
  )
}

export default App

// examples/vue-example.vue
<template>
  <div class="app">
    <h1>My Telegram Mini App</h1>
    <button @click="handleSubscribe">Subscribe</button>
    <button @click="handlePurchase">Purchase</button>
  </div>
</template>

<script setup>
/**
 * Dashgram SDK - Vue 3 Example
 *
 * Install the package: npm install @dashgram/javascript
 */

import { onMounted, onUnmounted } from "vue"
import DashgramMini from "@dashgram/javascript"

// Initialize SDK
DashgramMini.init({
  projectId: import.meta.env.VITE_DASHGRAM_PROJECT_ID || "your-project-id",
  apiKey: import.meta.env.VITE_DASHGRAM_API_KEY || "your-api-key",
  trackLevel: 2,
  debug: import.meta.env.DEV
})

// Track page view on mount
onMounted(() => {
  DashgramMini.track("screen_view", {
    screen_name: "home",
    screen_path: "/"
  })
})

// Flush events on unmount
onUnmounted(async () => {
  await DashgramMini.flush()
})

const handleSubscribe = () => {
  DashgramMini.track("subscription_started", {
    plan: "premium",
    price: 9.99
  })
  // Your subscription logic
}

const handlePurchase = () => {
  DashgramMini.track("purchase_completed", {
    product_id: "product-123",
    amount: 19.99,
    currency: "USD"
  })
  // Your purchase logic
}

// Example: Identify user
function identifyUser(userId, traits) {
  DashgramMini.identify(userId, traits)
}
</script>
